spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/taskdb
    username: task
    password: p@ssw0rd
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop #update
    show-sql: true
  mail:
    host: smtp.gmail.com  # Placeholder SMTP server
    port: 587
    username: zeinab00mmm@gmail.com    # Placeholder email username
    password: "yyrw njee adpx trgv"    # Placeholder email password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  report:
    email:
      to: zmm09228@gmail.com
server:
  port: 8080

logging:
  level:
    org:
      springframework: INFO
      hibernate: DEBUG

